kind: pipeline
name: syntax-and-phan

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: syntax-php7.4
  image: nextcloudci/php7.4:2
  commands:
    - composer install
    - ./lib/composer/bin/parallel-lint --exclude lib/composer/jakub-onderka/ --exclude 3rdparty/symfony/polyfill-php70/Resources/stubs/ --exclude 3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/ --exclude 3rdparty/paragonie/random_compat/lib/ --exclude lib/composer/composer/autoload_static.php --exclude 3rdparty/composer/autoload_static.php --exclude 3rdparty/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php .

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: nodb

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: nodb-php7.4
  image: nextcloudci/php7.4:2
  commands:
    - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite

services:
- name: cache
  image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: sqlite

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init
- name: sqlite-php7.4
  image: nextcloudci/php7.4:2
  commands:
    - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite

services:
- name: cache
  image: redis

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push


